### ISSUE TITLE
Cross hair for users when not painting

### ISSUE THREAD

**Issue by snoyface** [optexture/paint#6]
When users are not pressing the button to paint, they should have some ability to still see when they are. A cross hair would help for tracking where they are.

**Comment by t3kt** [comment]
In order to have the crosshairs not feed into the effects chain, we'll do this in a separate render pass which then gets composited over the output of the post processing chain. It'll create two copies of the instance channels, flip the status bit in one of them, and use it to render a different shape.
We'll need to make sure that we differentiate between a user being connected but not painting vs them not being connected anymore. This is the sort of thing that caused all the phantom paddles in bleepout. People disconnected but the system didn't recognize that so it continued rendering stuff for them.

**Comment by JimAnkrom** [comment]
There's a few issues on the trello board to address disconnection - but we
will need a way to tell touch designer that the user has disco'd.

I think sway usually keeps track of live users (via heartbeats) but it will
need to fire off a disco message to OSC on disco.

One thing I'm trying to design for tho is not just declaring someone
disco'd immediately; they should have some acceptable level of idle - we
don't want to requeue a player just because their phone went to sleep.

**Comment by snoyface** [comment]
@tekt so there is no way (without a 2nd render pass) to produce another
image without global effects on it? I assume that a second render pass with
just crosshairs and zero effects wouldn't be too hard on the processor.

What about have 2 states (with images that coinside) on the object, one is
painter dot/feedback and other is crosshair with global feedback = 0?

Jonathan MacLeod
Boston, MA
Contact = (978) 821-4637

**Comment by t3kt** [comment]
To use my metaphor from earlier discussions, it's like pouring two cups of water into a lake and trying to prevent one of them from swirling around.

**Comment by t3kt** [comment]
A second render pass isn't that big of a performance drain. If we can keep the calculations needed to prepare data for that second pass to a minimum, then it's fine. If we want some kind of radically different behavior/logic for that second pass, then that can be a problem.

**Comment by t3kt** [comment]
[example recording](https://vimeo.com/161562823/a4db47b44b)
